(function () {
  "use strict";

  window.QwicktonCategoryInits = window.QwicktonCategoryInits || {};

  const HISTORY_KEY = "qw-pdf-tools-history-v2";

  function safeNum(v, d = 0) {
    const n = Number(v);
    return Number.isFinite(n) ? n : d;
  }
  function esc(s) {
    return String(s || "").replace(/[&<>]/g, (m) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[m] || m));
  }
  function bytesToReadable(bytes) {
    if (!Number.isFinite(bytes)) return "-";
    const units = ["B", "KB", "MB", "GB"];
    let v = bytes;
    let i = 0;
    while (v >= 1024 && i < units.length - 1) {
      v /= 1024;
      i += 1;
    }
    return `${v.toFixed(i ? 2 : 0)} ${units[i]}`;
  }
  function setStatus(node, text, isError = false) {
    if (!node) return;
    node.textContent = text;
    node.classList.toggle("pdf-msg-error", !!isError);
    node.setAttribute("role", "status");
  }
  function copyText(text) {
    if (!text) return;
    navigator.clipboard?.writeText(String(text)).catch(() => {});
  }
  function downloadText(name, text) {
    const blob = new Blob([String(text || "")], { type: "text/plain;charset=utf-8" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = name;
    a.click();
    URL.revokeObjectURL(a.href);
  }
  function readFileAsDataURL(file) {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(String(reader.result || ""));
      reader.onerror = () => reject(new Error("Could not read file"));
      reader.readAsDataURL(file);
    });
  }
  function openPrintWindow(title, htmlBody, cssText) {
    const w = window.open("", "_blank", "width=1080,height=760");
    if (!w) return null;
    w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>${cssText}</style></head><body>${htmlBody}</body></html>`);
    w.document.close();
    w.focus();
    return w;
  }

  function readHistory() {
    try {
      return JSON.parse(localStorage.getItem(HISTORY_KEY) || "[]");
    } catch {
      return [];
    }
  }
  function writeHistory(items) {
    localStorage.setItem(HISTORY_KEY, JSON.stringify(items.slice(0, 30)));
  }

  function initPdfTools() {
    const grid = document.getElementById("categoryToolGrid");
    if (!grid || grid.dataset.pdfToolsInitialized === "true") return;
    grid.dataset.pdfToolsInitialized = "true";

    function makeCard(id, icon, title, bodyHtml, options = {}) {
      const focusable = options.focusable !== false;
      const card = document.createElement("div");
      card.className = "pdf-card";
      card.id = `card-${id}`;
      card.setAttribute("data-focusable", focusable ? "true" : "false");
      card.innerHTML = `<div class="pdf-card-header"><div class="pdf-card-icon">${icon}</div><h3 class="pdf-card-title">${esc(title)}</h3>${focusable ? '<button class="btn btn-secondary pdf-focus-btn" data-focus-open>Open</button><button class="btn btn-secondary pdf-focus-inline-close" data-focus-close>Close</button>' : ""}</div>${bodyHtml}`;
      grid.appendChild(card);
      return card;
    }

    let historyCardEl = null;
    function pushHistory(type, text) {
      if (!text) return;
      writeHistory([{ type, text: String(text).slice(0, 220), ts: Date.now() }, ...readHistory()]);
      renderHistory();
    }
    function renderHistory() {
      if (!historyCardEl) return;
      const list = historyCardEl.querySelector("#pdfHistoryList");
      const items = readHistory();
      if (!items.length) {
        list.innerHTML = '<span class="empty-hint">No PDF outputs yet.</span>';
        return;
      }
      list.innerHTML = items.map((item, idx) => `<button class="prompt-chip" data-i="${idx}"><strong>${esc(item.type)}:</strong> ${esc(item.text)}</button>`).join("");
      list.querySelectorAll("[data-i]").forEach((btn) => {
        btn.addEventListener("click", () => {
          const i = Number(btn.getAttribute("data-i"));
          copyText(`${items[i]?.type}: ${items[i]?.text}`);
        });
      });
    }

    // 1) Image to PDF layout
    const imageCard = makeCard("image", "🖼️", "Image to PDF Layout", `
      <p class="pdf-hint">Creates print-ready pages from images. Final PDF is generated by browser Print → Save as PDF.</p>
      <div><label>Images</label><input type="file" id="imgFiles" accept="image/jpeg,image/png,image/webp,image/bmp,image/gif" multiple></div>
      <div class="grid-2">
        <div><label>Page size</label><select id="imgPage"><option value="a4">A4</option><option value="letter">Letter</option></select></div>
        <div><label>Margin (mm)</label><input type="number" id="imgMargin" value="16" min="5" max="40"></div>
      </div>
      <div class="grid-2">
        <div><label>Image fit</label><select id="imgFit"><option value="contain">Contain</option><option value="cover">Cover</option></select></div>
        <div><label>Footer page numbers</label><select id="imgPageNo"><option value="yes">Yes</option><option value="no">No</option></select></div>
      </div>
      <div class="inline-row"><button class="btn btn-primary" id="imgOpenPdf">Open Print Layout</button><button class="btn btn-secondary" id="imgClear">Clear</button></div>
      <div id="imgStatus" class="result">Waiting for images.</div>
    `);
    let imageFiles = [];
    imageCard.querySelector("#imgFiles").addEventListener("change", (e) => {
      imageFiles = Array.from(e.target.files || []).filter((f) => f.type.startsWith("image/"));
      const total = imageFiles.reduce((sum, f) => sum + f.size, 0);
      setStatus(imageCard.querySelector("#imgStatus"), imageFiles.length ? `${imageFiles.length} image(s) selected (${bytesToReadable(total)})` : "Waiting for images.");
    });
    imageCard.querySelector("#imgClear").addEventListener("click", () => {
      imageFiles = [];
      imageCard.querySelector("#imgFiles").value = "";
      setStatus(imageCard.querySelector("#imgStatus"), "Waiting for images.");
    });
    imageCard.querySelector("#imgOpenPdf").addEventListener("click", async () => {
      const status = imageCard.querySelector("#imgStatus");
      if (!imageFiles.length) {
        setStatus(status, "Select at least one image.", true);
        return;
      }
      try {
        const urls = await Promise.all(imageFiles.map((f) => readFileAsDataURL(f)));
        const page = imageCard.querySelector("#imgPage").value;
        const margin = Math.max(5, Math.min(40, safeNum(imageCard.querySelector("#imgMargin").value, 16)));
        const fit = imageCard.querySelector("#imgFit").value === "cover" ? "cover" : "contain";
        const showNo = imageCard.querySelector("#imgPageNo").value === "yes";
        const pages = urls.map((u, i) => `<section class="pdf-image-page"><img src="${u}" alt="Image ${i + 1}">${showNo ? `<footer>Page ${i + 1}/${urls.length}</footer>` : ""}</section>`).join("");
        const w = openPrintWindow(
          "Image to PDF",
          pages,
          `@page{size:${page};margin:${margin}mm;}body{margin:0;background:#f3f4f6;font-family:Inter,Arial,sans-serif}.pdf-image-page{min-height:calc(100vh - 1px);page-break-after:always;display:flex;align-items:center;justify-content:center;background:#fff;position:relative}.pdf-image-page img{max-width:100%;max-height:calc(100vh - 35px);object-fit:${fit};display:block}.pdf-image-page footer{position:absolute;bottom:8px;right:14px;font-size:11px;color:#64748b}`
        );
        if (!w) {
          setStatus(status, "Popup blocked. Allow popups and try again.", true);
          return;
        }
        setStatus(status, "Layout opened. Use Print → Save as PDF.");
        pushHistory("Image→PDF", `${imageFiles.length} pages layout opened`);
        setTimeout(() => w.print(), 280);
      } catch {
        setStatus(status, "Could not prepare image layout.", true);
      }
    });

    // 2) Text to PDF
    const textCard = makeCard("text", "📝", "Text to PDF Document", `
      <div><label>Title</label><input type="text" id="txtTitle" placeholder="Document title"></div>
      <div><label>Content</label><textarea id="txtBody" rows="7" placeholder="Write your content..."></textarea></div>
      <div class="grid-2"><div><label>Font size</label><input type="number" id="txtSize" value="15" min="11" max="24"></div><div><label>Line height</label><input type="number" id="txtLine" value="1.6" min="1.2" max="2.2" step="0.1"></div></div>
      <div class="inline-row"><button class="btn btn-primary" id="txtOpenPdf">Open Print Document</button><button class="btn btn-secondary" id="txtTemplate">Load Template</button><button class="btn btn-secondary" id="txtExport">Download TXT</button></div>
      <div id="txtStatus" class="result">Write content and open print document.</div>
    `);
    textCard.querySelector("#txtTemplate").addEventListener("click", () => {
      textCard.querySelector("#txtBody").value = ["Executive Summary", "", "1. Objective", "2. Scope", "3. Deliverables", "4. Risks", "5. Timeline", "", `Prepared: ${new Date().toLocaleDateString()}`].join("\n");
      setStatus(textCard.querySelector("#txtStatus"), "Template loaded.");
    });
    textCard.querySelector("#txtExport").addEventListener("click", () => {
      const title = textCard.querySelector("#txtTitle").value.trim() || "document";
      const body = textCard.querySelector("#txtBody").value || "";
      downloadText(`${title.toLowerCase().replace(/[^a-z0-9]+/g, "-") || "document"}.txt`, body);
      pushHistory("Text export", `TXT downloaded (${title})`);
    });
    textCard.querySelector("#txtOpenPdf").addEventListener("click", () => {
      const title = textCard.querySelector("#txtTitle").value.trim() || "Text to PDF";
      const body = textCard.querySelector("#txtBody").value.trim();
      const size = Math.max(11, Math.min(24, safeNum(textCard.querySelector("#txtSize").value, 15)));
      const line = Math.max(1.2, Math.min(2.2, safeNum(textCard.querySelector("#txtLine").value, 1.6)));
      const status = textCard.querySelector("#txtStatus");
      if (!body) {
        setStatus(status, "Please enter content.", true);
        return;
      }
      const html = `<h1>${esc(title)}</h1><p class="meta">Generated ${esc(new Date().toLocaleString())}</p><div class="content">${esc(body).replace(/\n/g, "<br>")}</div>`;
      const w = openPrintWindow("Text PDF", html, `@page{size:a4;margin:18mm}body{font-family:Inter,Arial,sans-serif;color:#111827}h1{margin:0 0 14px}p.meta{font-size:12px;color:#6b7280;border-bottom:1px solid #e5e7eb;padding-bottom:10px}div.content{font-size:${size}px;line-height:${line};white-space:normal}`);
      if (!w) {
        setStatus(status, "Popup blocked. Allow popups and retry.", true);
        return;
      }
      setStatus(status, "Print document opened.");
      pushHistory("Text→PDF", title);
      setTimeout(() => w.print(), 220);
    });

    // 3) Viewer + inspector
    const viewCard = makeCard("viewer", "📄", "PDF Viewer & Inspector", `
      <div><label>Upload PDF</label><input type="file" id="viewFile" accept="application/pdf"></div>
      <div class="file-meta">
        <div><strong>Name</strong><span id="viewName">-</span></div>
        <div><strong>Size</strong><span id="viewSize">-</span></div>
        <div><strong>Type</strong><span id="viewType">-</span></div>
        <div><strong>Modified</strong><span id="viewDate">-</span></div>
      </div>
      <div class="inline-row"><button class="btn btn-secondary" id="viewOpen">Open Tab</button><button class="btn btn-secondary" id="viewPrint">Print</button><button class="btn btn-secondary" id="viewCopy">Copy Metadata</button></div>
      <div id="viewStatus" class="result">Upload a PDF to inspect and preview.</div>
      <div class="preview-wrap"><iframe id="viewFrame" title="PDF preview"></iframe></div>
    `);
    let currentPdfUrl = "";
    let currentPdfMeta = "";
    viewCard.querySelector("#viewFile").addEventListener("change", (e) => {
      const file = e.target.files?.[0];
      if (!file) return;
      if (currentPdfUrl) URL.revokeObjectURL(currentPdfUrl);
      currentPdfUrl = URL.createObjectURL(file);
      viewCard.querySelector("#viewFrame").src = currentPdfUrl;
      viewCard.querySelector("#viewName").textContent = file.name;
      viewCard.querySelector("#viewSize").textContent = bytesToReadable(file.size);
      viewCard.querySelector("#viewType").textContent = file.type || "application/pdf";
      viewCard.querySelector("#viewDate").textContent = new Date(file.lastModified).toLocaleString();
      currentPdfMeta = `${file.name} | ${bytesToReadable(file.size)} | ${file.type || "application/pdf"} | ${new Date(file.lastModified).toLocaleString()}`;
      setStatus(viewCard.querySelector("#viewStatus"), "PDF loaded.");
      pushHistory("PDF loaded", file.name);
    });
    viewCard.querySelector("#viewOpen").addEventListener("click", () => {
      const status = viewCard.querySelector("#viewStatus");
      if (!currentPdfUrl) {
        setStatus(status, "Upload a PDF first.", true);
        return;
      }
      window.open(currentPdfUrl, "_blank", "noopener,noreferrer");
      setStatus(status, "Opened in new tab.");
    });
    viewCard.querySelector("#viewPrint").addEventListener("click", () => {
      const status = viewCard.querySelector("#viewStatus");
      if (!currentPdfUrl) {
        setStatus(status, "Upload a PDF first.", true);
        return;
      }
      const w = window.open(currentPdfUrl, "_blank");
      if (!w) {
        setStatus(status, "Popup blocked. Allow popups.", true);
        return;
      }
      w.addEventListener("load", () => w.print());
      setStatus(status, "Print window opened.");
    });
    viewCard.querySelector("#viewCopy").addEventListener("click", () => copyText(currentPdfMeta));

    // 4) QA checklist
    const checklistCard = makeCard("checklist", "✅", "PDF Release Checklist", `
      <div><label>Context</label><input type="text" id="qcContext" placeholder="Client Proposal v3"></div>
      <div class="inline-row"><button class="btn btn-primary" id="qcGen">Generate</button><button class="btn btn-secondary" id="qcCopy">Copy</button><button class="btn btn-secondary" id="qcTxt">Download TXT</button></div>
      <textarea id="qcOut" class="result" rows="10" placeholder="Checklist appears here..."></textarea>
    `);
    checklistCard.querySelector("#qcGen").addEventListener("click", () => {
      const c = checklistCard.querySelector("#qcContext").value.trim() || "PDF Document";
      const lines = [
        `PDF Release Checklist - ${c}`,
        `Generated: ${new Date().toLocaleString()}`,
        "",
        "Quality",
        "- [ ] Page size/margins correct",
        "- [ ] Headings and typography consistent",
        "- [ ] No overflow/cut-off content",
        "",
        "Assets",
        "- [ ] Images are sharp and embedded",
        "- [ ] Links are valid",
        "",
        "Accessibility",
        "- [ ] Reading order and tags",
        "- [ ] Alt text for meaningful images",
        "- [ ] Sufficient color contrast",
        "",
        "Security/Meta",
        "- [ ] Metadata reviewed",
        "- [ ] Sensitive data removed",
        "- [ ] Final sign-off complete"
      ];
      checklistCard.querySelector("#qcOut").value = lines.join("\n");
      pushHistory("Checklist", c);
    });
    checklistCard.querySelector("#qcCopy").addEventListener("click", () => copyText(checklistCard.querySelector("#qcOut").value));
    checklistCard.querySelector("#qcTxt").addEventListener("click", () => downloadText("pdf-checklist.txt", checklistCard.querySelector("#qcOut").value));

    // 5) Merge sections
    const mergeCard = makeCard("mergeprint", "📑", "Merge Sections for PDF", `
      <div><label>Title</label><input type="text" id="mgTitle" placeholder="Merged Document"></div>
      <div><label>Section A</label><textarea id="mgA" rows="3"></textarea></div>
      <div><label>Section B</label><textarea id="mgB" rows="3"></textarea></div>
      <div><label>Section C</label><textarea id="mgC" rows="3"></textarea></div>
      <div class="inline-row"><button class="btn btn-primary" id="mgOpen">Open Print View</button><button class="btn btn-secondary" id="mgCopy">Copy Text</button></div>
      <div id="mgStatus" class="result">Combine sections and open print view.</div>
    `);
    mergeCard.querySelector("#mgCopy").addEventListener("click", () => {
      const txt = [mergeCard.querySelector("#mgTitle").value.trim(), "", mergeCard.querySelector("#mgA").value, "", mergeCard.querySelector("#mgB").value, "", mergeCard.querySelector("#mgC").value].join("\n");
      copyText(txt);
    });
    mergeCard.querySelector("#mgOpen").addEventListener("click", () => {
      const title = mergeCard.querySelector("#mgTitle").value.trim() || "Document";
      const html = `<h1>${esc(title)}</h1><h2>Section A</h2><p>${esc(mergeCard.querySelector("#mgA").value).replace(/\n/g, "<br>")}</p><h2>Section B</h2><p>${esc(mergeCard.querySelector("#mgB").value).replace(/\n/g, "<br>")}</p><h2>Section C</h2><p>${esc(mergeCard.querySelector("#mgC").value).replace(/\n/g, "<br>")}</p><p style="margin-top:24px;font-size:12px;color:#6b7280">Generated by Qwickton PDF Tools</p>`;
      const w = openPrintWindow(title, html, "@page{size:a4;margin:18mm}body{font-family:Inter,Arial,sans-serif;max-width:780px;margin:0 auto;line-height:1.6;color:#111827}h1{border-bottom:2px solid #111827;padding-bottom:8px}");
      if (!w) {
        setStatus(mergeCard.querySelector("#mgStatus"), "Popup blocked. Allow popups.", true);
        return;
      }
      setStatus(mergeCard.querySelector("#mgStatus"), "Print preview opened.");
      pushHistory("Merge→PDF", title);
      setTimeout(() => w.print(), 300);
    });

    // 6) Metadata template
    const metaCard = makeCard("pdfmeta", "🏷️", "Metadata Template", `
      <div class="grid-2"><div><label>Title</label><input type="text" id="mtTitle"></div><div><label>Author</label><input type="text" id="mtAuth"></div></div>
      <div class="grid-2"><div><label>Subject</label><input type="text" id="mtSub"></div><div><label>Keywords</label><input type="text" id="mtKey" placeholder="comma separated"></div></div>
      <div class="inline-row"><button class="btn btn-primary" id="mtGen">Generate</button><button class="btn btn-secondary" id="mtCopy">Copy</button><button class="btn btn-secondary" id="mtJson">Download JSON</button></div>
      <textarea id="mtOut" class="result" rows="5" readonly></textarea>
    `);
    let mtObj = null;
    metaCard.querySelector("#mtGen").addEventListener("click", () => {
      mtObj = {
        title: metaCard.querySelector("#mtTitle").value.trim() || "-",
        author: metaCard.querySelector("#mtAuth").value.trim() || "-",
        subject: metaCard.querySelector("#mtSub").value.trim() || "-",
        keywords: metaCard.querySelector("#mtKey").value.trim() || "-",
        generatedAt: new Date().toISOString()
      };
      metaCard.querySelector("#mtOut").value = [`Title: ${mtObj.title}`, `Author: ${mtObj.author}`, `Subject: ${mtObj.subject}`, `Keywords: ${mtObj.keywords}`].join("\n");
      pushHistory("Metadata", mtObj.title);
    });
    metaCard.querySelector("#mtCopy").addEventListener("click", () => copyText(metaCard.querySelector("#mtOut").value));
    metaCard.querySelector("#mtJson").addEventListener("click", () => {
      if (!mtObj) return;
      downloadText("pdf-metadata.json", JSON.stringify(mtObj, null, 2));
    });

    // 7) Page estimator
    const estCard = makeCard("pageest", "📏", "Page Budget Estimator", `
      <div class="grid-2"><div><label>Word count</label><input type="number" id="pgWords" value="2500" min="1"></div><div><label>Words/page</label><input type="number" id="pgWpp" value="350" min="50"></div></div>
      <div class="inline-row"><button class="btn btn-primary" id="pgRun">Estimate</button><button class="btn btn-secondary" id="pgCopy">Copy</button></div>
      <div id="pgOut" class="result">Estimate appears here.</div>
    `);
    estCard.querySelector("#pgRun").addEventListener("click", () => {
      const w = Math.max(1, safeNum(estCard.querySelector("#pgWords").value, 1));
      const p = Math.max(50, safeNum(estCard.querySelector("#pgWpp").value, 350));
      const pages = Math.ceil(w / p);
      const txt = `~${pages} page(s) at ${p} words/page (${w} words total)`;
      estCard.querySelector("#pgOut").textContent = txt;
      pushHistory("Page estimate", txt);
    });
    estCard.querySelector("#pgCopy").addEventListener("click", () => copyText(estCard.querySelector("#pgOut").textContent));

    // 8) Accessibility checklist
    const a11yCard = makeCard("pdfa11y", "♿", "Accessibility Checklist", `
      <div class="inline-row"><button class="btn btn-primary" id="a11yGen">Generate</button><button class="btn btn-secondary" id="a11yCopy">Copy</button><button class="btn btn-secondary" id="a11yTxt">Download TXT</button></div>
      <textarea id="a11yOut" class="result" rows="10" readonly></textarea>
    `);
    a11yCard.querySelector("#a11yGen").addEventListener("click", () => {
      const text = [
        "PDF Accessibility Checklist",
        `Generated: ${new Date().toLocaleString()}`,
        "",
        "- [ ] Language set",
        "- [ ] Tagged PDF structure",
        "- [ ] Proper heading hierarchy",
        "- [ ] Meaningful alt text",
        "- [ ] Tables with headers",
        "- [ ] Sufficient contrast",
        "- [ ] Keyboard focus order",
        "- [ ] Screen reader smoke test"
      ].join("\n");
      a11yCard.querySelector("#a11yOut").value = text;
      pushHistory("A11y checklist", "Generated");
    });
    a11yCard.querySelector("#a11yCopy").addEventListener("click", () => copyText(a11yCard.querySelector("#a11yOut").value));
    a11yCard.querySelector("#a11yTxt").addEventListener("click", () => downloadText("pdf-a11y-checklist.txt", a11yCard.querySelector("#a11yOut").value));

    // 9) Sign-off block
    const signCard = makeCard("signoff", "✍️", "Sign-off Block", `
      <div class="grid-2"><div><label>Reviewer</label><input type="text" id="sgName"></div><div><label>Role</label><input type="text" id="sgRole"></div></div>
      <div><label>Document ID</label><input type="text" id="sgDoc"></div>
      <div class="inline-row"><button class="btn btn-primary" id="sgGen">Generate</button><button class="btn btn-secondary" id="sgCopy">Copy</button><button class="btn btn-secondary" id="sgTxt">Download TXT</button></div>
      <textarea id="sgOut" class="result" rows="5" readonly></textarea>
    `);
    signCard.querySelector("#sgGen").addEventListener("click", () => {
      const n = signCard.querySelector("#sgName").value.trim() || "Reviewer";
      const r = signCard.querySelector("#sgRole").value.trim() || "Role";
      const d = signCard.querySelector("#sgDoc").value.trim() || "Document";
      const text = [`-- REVIEW SIGN-OFF --`, `Document: ${d}`, `Reviewer: ${n} (${r})`, `Date: ${new Date().toLocaleString()}`, `Status: APPROVED`].join("\n");
      signCard.querySelector("#sgOut").value = text;
      pushHistory("Sign-off", d);
    });
    signCard.querySelector("#sgCopy").addEventListener("click", () => copyText(signCard.querySelector("#sgOut").value));
    signCard.querySelector("#sgTxt").addEventListener("click", () => downloadText("pdf-signoff.txt", signCard.querySelector("#sgOut").value));

    // 10) SHA hash
    const hashCard = makeCard("pdfhash", "🔐", "SHA-256 Integrity Hash", `
      <div><label>File</label><input type="file" id="hsFile"></div>
      <div class="inline-row"><button class="btn btn-primary" id="hsRun">Compute</button><button class="btn btn-secondary" id="hsCopy">Copy</button></div>
      <div id="hsOut" class="result">Choose a file to hash.</div>
    `);
    hashCard.querySelector("#hsRun").addEventListener("click", async () => {
      const out = hashCard.querySelector("#hsOut");
      const f = hashCard.querySelector("#hsFile").files?.[0];
      if (!f) {
        setStatus(out, "Choose a file.", true);
        return;
      }
      if (!window.crypto?.subtle) {
        setStatus(out, "WebCrypto not available in this browser.", true);
        return;
      }
      try {
        const buf = await f.arrayBuffer();
        const dig = await crypto.subtle.digest("SHA-256", buf);
        const hex = [...new Uint8Array(dig)].map((b) => b.toString(16).padStart(2, "0")).join("");
        setStatus(out, hex);
        pushHistory("SHA-256", `${f.name} hashed`);
      } catch {
        setStatus(out, "Hashing failed.", true);
      }
    });
    hashCard.querySelector("#hsCopy").addEventListener("click", () => copyText(hashCard.querySelector("#hsOut").textContent));

    // 11) History
    historyCardEl = makeCard("history", "📜", "Recent PDF Outputs", `
      <div id="pdfHistoryList" class="chip-list"><span class="empty-hint">No PDF outputs yet.</span></div>
      <div class="inline-row"><button class="btn btn-secondary" id="histCopy">Copy All</button><button class="btn btn-secondary" id="histTxt">Export TXT</button><button class="btn btn-secondary" id="histClear">Clear</button></div>
    `, { focusable: false });
    historyCardEl.classList.add("full-width");
    historyCardEl.querySelector("#histCopy").addEventListener("click", () => copyText(readHistory().map((x) => `${x.type}: ${x.text}`).join("\n")));
    historyCardEl.querySelector("#histTxt").addEventListener("click", () => downloadText("pdf-tools-history.txt", readHistory().map((x, i) => `${i + 1}. ${x.type}: ${x.text}`).join("\n")));
    historyCardEl.querySelector("#histClear").addEventListener("click", () => {
      writeHistory([]);
      renderHistory();
    });
    renderHistory();

    // Focus modal
    const overlay = document.createElement("div");
    overlay.className = "pdf-focus-overlay";
    const host = document.createElement("div");
    host.className = "pdf-focus-host";
    document.body.appendChild(overlay);
    document.body.appendChild(host);
    let activeCard = null;
    let placeholder = null;
    function openFocus(card) {
      if (!card || activeCard === card) return;
      activeCard = card;
      placeholder = document.createElement("div");
      placeholder.style.height = `${card.offsetHeight}px`;
      card.parentNode.insertBefore(placeholder, card);
      host.appendChild(card);
      card.classList.add("is-focused");
      card.querySelector("[data-focus-open]")?.classList.add("is-hidden");
      card.querySelector("[data-focus-close]")?.classList.add("active");
      overlay.classList.add("active");
      host.classList.add("active");
      document.body.classList.add("pdf-modal-open");
    }
    function closeFocus() {
      if (!activeCard) return;
      activeCard.querySelector("[data-focus-open]")?.classList.remove("is-hidden");
      activeCard.querySelector("[data-focus-close]")?.classList.remove("active");
      activeCard.classList.remove("is-focused");
      if (placeholder?.parentNode) {
        placeholder.parentNode.insertBefore(activeCard, placeholder);
        placeholder.remove();
      }
      activeCard = null;
      placeholder = null;
      overlay.classList.remove("active");
      host.classList.remove("active");
      document.body.classList.remove("pdf-modal-open");
    }
    grid.querySelectorAll(".pdf-card [data-focus-open]").forEach((btn) => btn.addEventListener("click", (e) => openFocus(e.target.closest(".pdf-card"))));
    grid.querySelectorAll(".pdf-card [data-focus-close]").forEach((btn) => btn.addEventListener("click", (e) => {
      e.stopPropagation();
      closeFocus();
    }));
    overlay.addEventListener("click", closeFocus);
    document.addEventListener("keydown", (e) => {
      if (e.key === "Escape") closeFocus();
    });

    document.querySelectorAll(".tool-nav-btn").forEach((btn) => {
      btn.addEventListener("click", () => {
        document.querySelectorAll(".tool-nav-btn").forEach((b) => b.classList.remove("active"));
        btn.classList.add("active");
        const target = btn.getAttribute("data-target");
        const card = document.getElementById(`card-${target}`);
        if (!card) return;
        const mobile = window.matchMedia("(max-width: 768px)").matches;
        if (mobile) openFocus(card);
        else card.scrollIntoView({ behavior: "smooth", block: "start" });
      });
    });

    const yearEl = document.getElementById("year");
    if (yearEl) yearEl.textContent = String(new Date().getFullYear());
  }

  window.QwicktonCategoryInits["pdf-tools"] = initPdfTools;
  document.addEventListener("DOMContentLoaded", () => {
    if (document.getElementById("categoryToolGrid") && !window._qwCategoryBootstrapped) initPdfTools();
  });
})();
/**
 * PDF TOOLS - Complete JavaScript
 * Tools: Image to PDF, Text to PDF, PDF Viewer & Inspector, Release Checklist
 * Architecture: IIFE module, global register, double-init protection
 */

(function() {
  "use strict";

  // Register in global QwicktonCategoryInits
  window.QwicktonCategoryInits = window.QwicktonCategoryInits || {};

  // ============================================
  // UTILITY FUNCTIONS
  // ============================================
  function safeNum(v, d = 0) { let n = Number(v); return isFinite(n) ? n : d; }
  
  function escapeHtml(s) {
    return String(s || "").replace(/[&<>]/g, function(m) {
      if (m === '&') return '&amp;';
      if (m === '<') return '&lt;';
      if (m === '>') return '&gt;';
      return m;
    });
  }
  
  function copyText(text) { 
    if (text) navigator.clipboard?.writeText(String(text)).catch(() => {}); 
  }
  
  function bytesToReadable(bytes) {
    if (!Number.isFinite(bytes)) return "-";
    const units = ["B", "KB", "MB", "GB"];
    let value = bytes;
    let unit = 0;
    while (value >= 1024 && unit < units.length - 1) {
      value /= 1024;
      unit++;
    }
    return `${value.toFixed(2)} ${units[unit]}`;
  }
  
  function readFileAsDataURL(file) {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result);
      reader.onerror = () => reject(new Error("Could not read file"));
      reader.readAsDataURL(file);
    });
  }

  // ============================================
  // CARD CREATION
  // ============================================
  function initPdfTools(api) {
    const grid = document.getElementById("categoryToolGrid");
    if (!grid) return;
    if (grid.dataset.pdfToolsInitialized === "true") return;
    grid.dataset.pdfToolsInitialized = "true";

    function makeCard(id, icon, title, bodyHtml, options = {}) {
      const focusable = options.focusable !== false;
      const card = document.createElement("div");
      card.className = "pdf-card";
      card.id = `card-${id}`;
      card.setAttribute("data-tool", id);
      card.setAttribute("data-focusable", focusable ? "true" : "false");
      card.innerHTML = `
        <div class="pdf-card-header">
          <div class="pdf-card-icon">${icon}</div>
          <h3 class="pdf-card-title">${escapeHtml(title)}</h3>
          ${focusable ? `
            <button class="btn btn-secondary pdf-focus-btn" data-focus-open>Open</button>
            <button class="btn btn-secondary pdf-focus-inline-close" data-focus-close>Close</button>
          ` : ""}
        </div>
        ${bodyHtml}
      `;
      grid.appendChild(card);
      return card;
    }

    // ============================================
    // IMAGE TO PDF CARD
    // ============================================
    const imageCard = makeCard("image", "🖼️", "Image to PDF Pro", `
      <div><label>Select Images</label><input type="file" id="pdfImageInput" accept="image/jpeg,image/png,image/webp,image/gif,image/bmp" multiple></div>
      <div class="grid-2">
        <div><label>Page Size</label><select id="pdfPageSize">
          <option value="a4">A4 (210 × 297 mm)</option>
          <option value="letter">Letter (216 × 279 mm)</option>
        </select></div>
        <div><label>Margin</label><select id="pdfPageMargin">
          <option value="12">Compact (12mm)</option>
          <option value="20" selected>Standard (20mm)</option>
          <option value="32">Wide (32mm)</option>
        </select></div>
      </div>
      <div class="inline-row">
        <button class="btn btn-primary" id="pdfImagePrintBtn">🖨️ Open PDF Layout</button>
        <button class="btn btn-secondary" id="pdfImageClearBtn">🗑️ Clear</button>
      </div>
      <div id="pdfImageResult" class="result">📷 Status: waiting for images</div>
    `);

    let imageFiles = [];
    
    imageCard.querySelector("#pdfImageInput").addEventListener("change", (e) => {
      const files = Array.from(e.target.files || []).filter(file => file.type.startsWith("image/"));
      imageFiles = files;
      const result = imageCard.querySelector("#pdfImageResult");
      if (!files.length) {
        result.innerHTML = "📷 Status: waiting for images";
        return;
      }
      const totalSize = files.reduce((sum, file) => sum + file.size, 0);
      result.innerHTML = `✅ Selected ${files.length} image(s), ${bytesToReadable(totalSize)} total`;
    });
    
    imageCard.querySelector("#pdfImageClearBtn").addEventListener("click", () => {
      imageFiles = [];
      imageCard.querySelector("#pdfImageInput").value = "";
      imageCard.querySelector("#pdfImageResult").innerHTML = "📷 Status: waiting for images";
    });
    
    imageCard.querySelector("#pdfImagePrintBtn").addEventListener("click", async () => {
      if (!imageFiles.length) {
        imageCard.querySelector("#pdfImageResult").innerHTML = "⚠️ Please select images first";
        return;
      }
      const pageSize = imageCard.querySelector("#pdfPageSize").value;
      const margin = Number(imageCard.querySelector("#pdfPageMargin").value) || 20;
      const urls = await Promise.all(imageFiles.map(file => readFileAsDataURL(file)));
      const w = window.open("", "_blank", "width=1080,height=760");
      const pages = urls.map((url, index) => `
        <section class="pdf-page">
          <img src="${url}" alt="Image ${index + 1}">
          <footer>📄 Page ${index + 1} / ${urls.length}</footer>
        </section>
      `).join("");
      
      w.document.write(`
        <html>
          <head>
            <title>Image to PDF - Qwickton</title>
            <style>
              @page { size: ${pageSize}; margin: ${margin}mm; }
              body { margin: 0; font-family: 'Inter', Arial, sans-serif; background: #f3f4f6; }
              .pdf-page {
                page-break-after: always;
                min-height: calc(100vh - 2px);
                display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: center;
                background: white;
                position: relative;
              }
              .pdf-page img { 
                max-width: 100%; 
                max-height: calc(100vh - 60px); 
                display: block;
                object-fit: contain;
              }
              .pdf-page footer { 
                position: absolute; 
                bottom: 12px; 
                right: 16px; 
                font-size: 11px; 
                color: #64748b;
                font-family: monospace;
              }
            </style>
          </head>
          <body>${pages}</body>
        </html>
      `);
      w.document.close();
      w.focus();
      setTimeout(() => w.print(), 300);
    });

    // ============================================
    // TEXT TO PDF CARD
    // ============================================
    const textCard = makeCard("text", "📝", "Text to PDF Pro", `
      <div><label>Document Title</label><input type="text" id="pdfTextTitle" placeholder="Document title (optional)"></div>
      <div><label>Content</label><textarea id="pdfTextInput" rows="6" placeholder="Enter your content here..."></textarea></div>
      <div class="grid-2">
        <div><label>Font Size (px)</label><input type="number" id="pdfTextFontSize" min="12" max="22" value="15"></div>
        <div><label>Line Height</label><input type="number" id="pdfTextLineHeight" min="1.2" max="2.1" step="0.1" value="1.6"></div>
      </div>
      <div class="inline-row">
        <button class="btn btn-primary" id="pdfTextPrintBtn">🖨️ Open Print-Ready Text</button>
        <button class="btn btn-secondary" id="pdfTextTemplateBtn">📋 Load Template</button>
      </div>
      <div id="pdfTextResult" class="result">📝 Client-side export via browser Save as PDF (Ctrl+P / Cmd+P)</div>
    `);

    textCard.querySelector("#pdfTextTemplateBtn").addEventListener("click", () => {
      const template = [
        "Executive Summary",
        "",
        "1. Objective",
        "2. Scope of Work",
        "3. Key Deliverables",
        "4. Timeline",
        "5. Budget Overview",
        "",
        "",
        "Prepared using Qwickton PDF Tools",
        new Date().toLocaleDateString()
      ].join("\n");
      textCard.querySelector("#pdfTextInput").value = template;
      textCard.querySelector("#pdfTextResult").innerHTML = "✅ Template loaded. Edit and export as PDF.";
    });
    
    textCard.querySelector("#pdfTextPrintBtn").addEventListener("click", () => {
      const title = textCard.querySelector("#pdfTextTitle").value.trim() || "Text to PDF";
      const text = textCard.querySelector("#pdfTextInput").value.trim();
      const fontSize = Math.max(12, Math.min(22, Number(textCard.querySelector("#pdfTextFontSize").value) || 15));
      const lineHeight = Math.max(1.2, Math.min(2.1, Number(textCard.querySelector("#pdfTextLineHeight").value) || 1.6));
      
      if (!text) {
        textCard.querySelector("#pdfTextResult").innerHTML = "⚠️ Please enter some text content";
        return;
      }
      
      const w = window.open("", "_blank", "width=980,height=760");
      w.document.write(`
        <html>
          <head>
            <title>${escapeHtml(title)}</title>
            <style>
              @page { size: a4; margin: 18mm; }
              body { 
                font-family: 'Inter', 'Segoe UI', Arial, sans-serif; 
                padding: 0; 
                color: #0f172a;
                line-height: ${lineHeight};
              }
              h1 { font-size: 24px; font-weight: 700; margin: 0 0 16px; color: #0f172a; }
              .meta { 
                font-size: 12px; 
                color: #64748b; 
                margin-bottom: 24px; 
                padding-bottom: 12px;
                border-bottom: 1px solid #e2e8f0;
              }
              .content { 
                white-space: pre-wrap; 
                font-size: ${fontSize}px; 
                line-height: ${lineHeight};
              }
            </style>
          </head>
          <body>
            <h1>${escapeHtml(title)}</h1>
            <div class="meta">📅 Generated on ${escapeHtml(new Date().toLocaleString())}</div>
            <div class="content">${escapeHtml(text)}</div>
          </body>
        </html>
      `);
      w.document.close();
      w.focus();
      setTimeout(() => w.print(), 200);
    });

    // ============================================
    // PDF VIEWER & INSPECTOR CARD
    // ============================================
    const viewerCard = makeCard("viewer", "📄", "PDF Viewer & Inspector", `
      <div><label>Upload PDF</label><input type="file" id="pdfViewerInput" accept="application/pdf"></div>
      <div class="file-meta" id="pdfMeta">
        <div><strong>📄 Name</strong><span id="pdfMetaName">-</span></div>
        <div><strong>📦 Size</strong><span id="pdfMetaSize">-</span></div>
        <div><strong>📁 Type</strong><span id="pdfMetaType">-</span></div>
        <div><strong>🕒 Modified</strong><span id="pdfMetaDate">-</span></div>
      </div>
      <div class="inline-row">
        <button class="btn btn-secondary" id="pdfViewerOpenBtn">🔗 Open in New Tab</button>
        <button class="btn btn-secondary" id="pdfViewerPrintBtn">🖨️ Print PDF</button>
      </div>
      <div class="preview-wrap">
        <iframe id="pdfViewerFrame" title="PDF Preview" style="width:100%; min-height:450px; border:0;"></iframe>
      </div>
    `);

    let currentPdfUrl = "";
    
    viewerCard.querySelector("#pdfViewerInput").addEventListener("change", (e) => {
      const file = e.target.files?.[0];
      if (!file) return;
      if (currentPdfUrl) URL.revokeObjectURL(currentPdfUrl);
      currentPdfUrl = URL.createObjectURL(file);
      viewerCard.querySelector("#pdfViewerFrame").src = currentPdfUrl;
      viewerCard.querySelector("#pdfMetaName").textContent = file.name;
      viewerCard.querySelector("#pdfMetaSize").textContent = bytesToReadable(file.size);
      viewerCard.querySelector("#pdfMetaType").textContent = file.type || "application/pdf";
      viewerCard.querySelector("#pdfMetaDate").textContent = new Date(file.lastModified).toLocaleString();
    });
    
    viewerCard.querySelector("#pdfViewerOpenBtn").addEventListener("click", () => {
      if (!currentPdfUrl) {
        alert("Please upload a PDF file first");
        return;
      }
      window.open(currentPdfUrl, "_blank");
    });
    
    viewerCard.querySelector("#pdfViewerPrintBtn").addEventListener("click", () => {
      if (!currentPdfUrl) {
        alert("Please upload a PDF file first");
        return;
      }
      const w = window.open(currentPdfUrl, "_blank");
      if (w) {
        w.addEventListener("load", () => w.print());
      }
    });

    // ============================================
    // PDF RELEASE CHECKLIST CARD
    // ============================================
    const checklistCard = makeCard("checklist", "✅", "PDF Release Checklist", `
      <div><label>Document Name / Context</label><input type="text" id="pdfChecklistInput" placeholder="Document name or project context"></div>
      <div class="inline-row">
        <button class="btn btn-primary" id="pdfChecklistBtn">📋 Generate Checklist</button>
        <button class="btn btn-secondary" id="pdfChecklistCopyBtn">📋 Copy</button>
      </div>
      <textarea id="pdfChecklistOutput" class="result" rows="8" placeholder="Checklist output will appear here..."></textarea>
    `);

    checklistCard.querySelector("#pdfChecklistBtn").addEventListener("click", () => {
      const context = checklistCard.querySelector("#pdfChecklistInput").value.trim() || "PDF Document";
      const lines = [
        "╔══════════════════════════════════════════════════════════════╗",
        `║           PDF RELEASE CHECKLIST - ${context.padEnd(25).slice(0, 25)}║`,
        "╚══════════════════════════════════════════════════════════════╝",
        "",
        "📄 DOCUMENT QUALITY",
        "├─ ☐ Verify page size and margins are correct",
        "├─ ☐ Check heading hierarchy and formatting",
        "├─ ☐ Ensure consistent font usage throughout",
        "├─ ☐ Verify line spacing and paragraph spacing",
        "",
        "🖼️ IMAGES & MEDIA",
        "├─ ☐ Check image resolution (minimum 150 DPI for print)",
        "├─ ☐ Verify all images are properly embedded",
        "├─ ☐ Check image captions and alt text",
        "├─ ☐ Ensure no broken image references",
        "",
        "🔗 LINKS & REFERENCES",
        "├─ ☐ Test all hyperlinks (if applicable)",
        "├─ ☐ Verify table of contents links",
        "├─ ☐ Check cross-references are correct",
        "├─ ☐ Ensure page numbers are accurate",
        "",
        "🎨 COLOR & FORMATTING",
        "├─ ☐ Verify color consistency (CMYK for print, RGB for web)",
        "├─ ☐ Check contrast for accessibility",
        "├─ ☐ Ensure no missing fonts",
        "├─ ☐ Verify bleeds and trim marks (for print)",
        "",
        "🔒 SECURITY & METADATA",
        "├─ ☐ Review document properties (title, author, subject)",
        "├─ ☐ Set appropriate permissions if needed",
        "├─ ☐ Add watermarks if required",
        "├─ ☐ Verify no hidden sensitive data",
        "",
        "✅ FINAL VERIFICATION",
        "├─ ☐ Run final spell check",
        "├─ ☐ Preview on different devices",
        "├─ ☐ Test print a sample page",
        "├─ ☐ Get final approval signature",
        "",
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
        `📅 Generated: ${new Date().toLocaleString()}`,
        "🏷️ Tool: Qwickton PDF Tools"
      ].join("\n");
      
      checklistCard.querySelector("#pdfChecklistOutput").value = lines;
    });
    
    checklistCard.querySelector("#pdfChecklistCopyBtn").addEventListener("click", () => {
      copyText(checklistCard.querySelector("#pdfChecklistOutput").value);
    });

    // ============================================
    // MERGED TEXT → PRINT (save as PDF from browser)
    // ============================================
    const mergeCard = makeCard("mergeprint", "📑", "Merge Text for Print / PDF", `
      <p class="small">Combine sections, then use your browser Print → Save as PDF.</p>
      <div><label>Title</label><input type="text" id="mpTitle" placeholder="Document title"></div>
      <div><label>Section A</label><textarea id="mpA" rows="3" placeholder="Introduction…"></textarea></div>
      <div><label>Section B</label><textarea id="mpB" rows="3"></textarea></div>
      <div><label>Section C</label><textarea id="mpC" rows="3"></textarea></div>
      <div class="inline-row">
        <button class="btn btn-primary" id="mpPreview">Open print preview</button>
        <button class="btn btn-secondary" id="mpCopy">Copy plain text</button>
      </div>
    `);
    mergeCard.querySelector("#mpCopy").onclick = () => {
      const t = [
        mergeCard.querySelector("#mpTitle").value.trim(),
        "",
        mergeCard.querySelector("#mpA").value,
        "",
        mergeCard.querySelector("#mpB").value,
        "",
        mergeCard.querySelector("#mpC").value
      ].join("\n");
      copyText(t);
    };
    mergeCard.querySelector("#mpPreview").onclick = () => {
      const title = mergeCard.querySelector("#mpTitle").value.trim() || "Document";
      const body = ["<h1>", escapeHtml(title), "</h1>"]
        .concat(["<h2>Section A</h2><p>", escapeHtml(mergeCard.querySelector("#mpA").value).replace(/\n/g, "<br>"), "</p>"])
        .concat(["<h2>Section B</h2><p>", escapeHtml(mergeCard.querySelector("#mpB").value).replace(/\n/g, "<br>"), "</p>"])
        .concat(["<h2>Section C</h2><p>", escapeHtml(mergeCard.querySelector("#mpC").value).replace(/\n/g, "<br>"), "</p>"])
        .join("");
      const w = window.open("", "_blank");
      if (!w) return;
      w.document.write(`<!DOCTYPE html><html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title>
        <style>body{font-family:system-ui,sans-serif;max-width:720px;margin:2rem auto;padding:0 1rem;line-height:1.6}h1{border-bottom:2px solid #333}</style></head><body>${body}<p style="margin-top:2rem;color:#666;font-size:12px">Printed from Qwickton PDF Tools</p></body></html>`);
      w.document.close();
      w.focus();
      setTimeout(() => w.print(), 400);
    };

    // ============================================
    // PDF METADATA TEMPLATE
    // ============================================
    const metaCard = makeCard("pdfmeta", "🏷️", "PDF Metadata Template", `
      <div class="grid-2">
        <div><label>Title</label><input type="text" id="pmTitle"></div>
        <div><label>Author</label><input type="text" id="pmAuth"></div>
      </div>
      <div class="grid-2">
        <div><label>Subject</label><input type="text" id="pmSub"></div>
        <div><label>Keywords</label><input type="text" id="pmKey" placeholder="comma separated"></div>
      </div>
      <div class="inline-row">
        <button class="btn btn-primary" id="pmGen">Generate</button>
        <button class="btn btn-secondary" id="pmCopy">Copy</button>
      </div>
      <textarea id="pmOut" class="result" rows="5" readonly></textarea>
    `);
    metaCard.querySelector("#pmGen").onclick = () => {
      const lines = [
        `Title: ${metaCard.querySelector("#pmTitle").value.trim() || "-"}`,
        `Author: ${metaCard.querySelector("#pmAuth").value.trim() || "-"}`,
        `Subject: ${metaCard.querySelector("#pmSub").value.trim() || "-"}`,
        `Keywords: ${metaCard.querySelector("#pmKey").value.trim() || "-"}`
      ];
      metaCard.querySelector("#pmOut").value = lines.join("\n");
    };
    metaCard.querySelector("#pmCopy").onclick = () => copyText(metaCard.querySelector("#pmOut").value);

    // ============================================
    // PAGE BUDGET ESTIMATOR
    // ============================================
    const pageEstCard = makeCard("pageest", "📄", "Page Count Estimator", `
      <div class="grid-2">
        <div><label>Word count</label><input type="number" id="peWords" value="2500" min="1"></div>
        <div><label>Words per page</label><input type="number" id="peWpp" value="350" min="50"></div>
      </div>
      <div class="inline-row">
        <button class="btn btn-primary" id="peBtn">Estimate</button>
      </div>
      <div id="peOut" class="result">—</div>
    `);
    pageEstCard.querySelector("#peBtn").onclick = () => {
      const w = safeNum(pageEstCard.querySelector("#peWords").value, 1);
      const p = safeNum(pageEstCard.querySelector("#peWpp").value, 350);
      const pages = Math.max(1, Math.ceil(w / p));
      pageEstCard.querySelector("#peOut").textContent = `≈ ${pages} page(s) at ${p} words/page (${w} words).`;
    };

    // ============================================
    // PDF ACCESSIBILITY CHECKLIST
    // ============================================
    const a11yCard = makeCard("pdfa11y", "♿", "PDF Accessibility Checklist", `
      <div class="inline-row">
        <button class="btn btn-primary" id="a11yGen">Generate checklist</button>
        <button class="btn btn-secondary" id="a11yCopy">Copy</button>
      </div>
      <textarea id="a11yOut" class="result" rows="12" readonly></textarea>
    `);
    a11yCard.querySelector("#a11yGen").onclick = () => {
      a11yCard.querySelector("#a11yOut").value = [
        "PDF Accessibility (WCAG-oriented) — review checklist",
        "☐ Document language set",
        "☐ Logical reading order / tags",
        "☐ All images have alternate text",
        "☐ Headings structured (H1→H2→H3)",
        "☐ Contrast sufficient for body text",
        "☐ Links have descriptive text",
        "☐ Tables have headers defined",
        "☐ Forms have labels and tab order",
        "☐ Screen reader smoke test done",
        `Generated ${new Date().toLocaleString()}`
      ].join("\n");
    };
    a11yCard.querySelector("#a11yCopy").onclick = () => copyText(a11yCard.querySelector("#a11yOut").value);

    // ============================================
    // SIGN-OFF STAMP TEXT
    // ============================================
    const signCard = makeCard("signoff", "✍️", "Review Sign-Off Block", `
      <div class="grid-2">
        <div><label>Reviewer</label><input type="text" id="soName" placeholder="Name"></div>
        <div><label>Role</label><input type="text" id="soRole" placeholder="QA / Legal"></div>
      </div>
      <div><label>Document ID</label><input type="text" id="soDoc" placeholder="DOC-2024-001"></div>
      <div class="inline-row">
        <button class="btn btn-primary" id="soBtn">Generate block</button>
        <button class="btn btn-secondary" id="soCopy">Copy</button>
      </div>
      <textarea id="soOut" class="result" rows="5" readonly></textarea>
    `);
    signCard.querySelector("#soBtn").onclick = () => {
      const n = signCard.querySelector("#soName").value.trim() || "Reviewer";
      const r = signCard.querySelector("#soRole").value.trim() || "Role";
      const d = signCard.querySelector("#soDoc").value.trim() || "Document";
      signCard.querySelector("#soOut").value = [
        "— REVIEW SIGN-OFF —",
        `Document: ${d}`,
        `Reviewer: ${n} (${r})`,
        `Date: ${new Date().toLocaleString()}`,
        "Status: APPROVED FOR RELEASE"
      ].join("\n");
    };
    signCard.querySelector("#soCopy").onclick = () => copyText(signCard.querySelector("#soOut").value);

    // ============================================
    // FILE SHA-256 (integrity for PDFs & any file)
    // ============================================
    const hashCard = makeCard("pdfhash", "🔐", "File SHA-256 (integrity)", `
      <div><label>File</label><input type="file" id="phFile"></div>
      <div class="inline-row">
        <button class="btn btn-primary" id="phBtn">Compute hash</button>
        <button class="btn btn-secondary" id="phCopy">Copy hash</button>
      </div>
      <div id="phOut" class="result" style="word-break:break-all">—</div>
    `);
    hashCard.querySelector("#phBtn").onclick = async () => {
      const f = hashCard.querySelector("#phFile").files?.[0];
      if (!f) {
        hashCard.querySelector("#phOut").textContent = "Choose a file.";
        return;
      }
      if (!window.crypto?.subtle) {
        hashCard.querySelector("#phOut").textContent = "Web Crypto not available.";
        return;
      }
      const buf = await f.arrayBuffer();
      const dig = await crypto.subtle.digest("SHA-256", buf);
      const hex = [...new Uint8Array(dig)].map((b) => b.toString(16).padStart(2, "0")).join("");
      hashCard.querySelector("#phOut").textContent = hex;
    };
    hashCard.querySelector("#phCopy").onclick = () => copyText(hashCard.querySelector("#phOut").textContent);

    // ============================================
    // FOCUS MODAL SYSTEM
    // ============================================
    const focusOverlay = document.createElement("div");
    focusOverlay.className = "pdf-focus-overlay";
    const focusHost = document.createElement("div");
    focusHost.className = "pdf-focus-host";
    document.body.appendChild(focusOverlay);
    document.body.appendChild(focusHost);

    let activeFocusedCard = null;
    let focusPlaceholder = null;
    let focusOpenTimer = null;

    function openToolFocus(card) {
      if (!card) return;
      if (focusOpenTimer) clearTimeout(focusOpenTimer);
      if (activeFocusedCard === card) return;
      if (activeFocusedCard) activeFocusedCard.classList.remove("is-focused");
      activeFocusedCard = card;
      focusPlaceholder = document.createElement("div");
      focusPlaceholder.style.height = card.offsetHeight + "px";
      card.parentNode.insertBefore(focusPlaceholder, card);
      focusHost.appendChild(card);
      card.classList.add("is-focused");
      card.querySelector("[data-focus-open]")?.classList.add("is-hidden");
      card.querySelector("[data-focus-close]")?.classList.add("active");
      document.body.classList.add("pdf-modal-open");
      focusOverlay.classList.add("active");
      focusHost.classList.add("active");
      setTimeout(() => {
        const firstInput = card.querySelector("input, select, textarea, button");
        firstInput?.focus();
      }, 40);
    }

    function closeToolFocus() {
      if (focusOpenTimer) clearTimeout(focusOpenTimer);
      if (!activeFocusedCard) return;
      activeFocusedCard.querySelector("[data-focus-open]")?.classList.remove("is-hidden");
      activeFocusedCard.querySelector("[data-focus-close]")?.classList.remove("active");
      activeFocusedCard.classList.remove("is-focused");
      if (focusPlaceholder?.parentNode) {
        focusPlaceholder.parentNode.insertBefore(activeFocusedCard, focusPlaceholder);
        focusPlaceholder.remove();
      }
      focusPlaceholder = null;
      activeFocusedCard = null;
      focusHost.classList.remove("active");
      focusOverlay.classList.remove("active");
      document.body.classList.remove("pdf-modal-open");
    }

    grid.querySelectorAll(".pdf-card [data-focus-open]").forEach(btn => {
      btn.addEventListener("click", (e) => openToolFocus(e.target.closest(".pdf-card")));
    });
    
    grid.querySelectorAll(".pdf-card [data-focus-close]").forEach(btn => {
      btn.addEventListener("click", (e) => { e.stopPropagation(); closeToolFocus(); });
    });
    
    grid.querySelectorAll(".pdf-card[data-focusable='true'] .pdf-card-header").forEach(header => {
      header.addEventListener("click", (e) => {
        if (e.target.closest("[data-focus-open], [data-focus-close], button, input, select, textarea, a")) return;
        openToolFocus(e.currentTarget.closest(".pdf-card"));
      });
    });
    
    focusOverlay.addEventListener("click", () => closeToolFocus());
    document.addEventListener("keydown", (e) => { if (e.key === "Escape") closeToolFocus(); });

    // ============================================
    // NAVIGATION BUTTONS
    // ============================================
    document.querySelectorAll(".tool-nav-btn").forEach(btn => {
      btn.addEventListener("click", () => {
        document.querySelectorAll(".tool-nav-btn").forEach(b => b.classList.remove("active"));
        btn.classList.add("active");
        const target = btn.getAttribute("data-target");
        const card = document.getElementById(`card-${target}`);
        if (!card) return;
        const mobileLike = window.matchMedia("(max-width: 768px)").matches;
        if (mobileLike) {
          openToolFocus(card);
        } else {
          card.scrollIntoView({ behavior: "smooth", block: "start" });
          focusOpenTimer = setTimeout(() => openToolFocus(card), 200);
        }
      });
    });

    // ============================================
    // Footer year
    const yearEl = document.getElementById("year");
    if (yearEl) yearEl.textContent = String(new Date().getFullYear());
  }

  // Register the init function
  window.QwicktonCategoryInits["pdf-tools"] = initPdfTools;

  // Fallback auto-init if bootstrap missing
  document.addEventListener("DOMContentLoaded", () => {
    if (document.getElementById("categoryToolGrid") && !window._qwCategoryBootstrapped) {
      initPdfTools(null);
    }
  });
})();